# Generated by Django 4.2.3 on 2023-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_field',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
