# Generated by Django 4.2.3 on 2023-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookfile',
            field=models.FileField(upload_to='book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverimg',
            field=models.ImageField(upload_to='cover/'),
        ),
    ]
