# Generated by Django 4.2.3 on 2023-07-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_book_bookfile_alter_book_coverimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reporter',
        ),
    ]
